[config]

[templates.nvim-base16]
input_path = "~/.config/matugen/templates/nvim.lua"
output_path = "~/.config/nvim/lua/matugen.lua"
post_hook = 'pkill -SIGUSR1 nvim'

[templates.discord]
input_path = '~/.config/matugen/templates/matugen-discord.css'
output_path = '~/.config/Vencord/themes/matugen-discord.css'

[templates.grub]
input_path  = '~/.config/matugen/templates/grub2-theme.txt.in'
output_path = '~/Themes/GRUB/theme.txt'
post_hook = 'systemctl start matugen.service'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/rofi-colors.rasi'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.walker]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/walker/colors.css'

#[templates.nwgdock]
#input_path = '~/.config/matugen/templates/colors.css'
#output_path = '~/.config/nwg-dock-hyprland/colors.css'

[templates.sequences]
input_path = '~/.config/matugen/templates/sequences'
output_path = '~/.cache/wal/sequences'

[templates.primary]
input_path = '~/.config/matugen/templates/primary'
output_path = '~/.config/ml4w/colors/primary'

[templates.secondary]
input_path = '~/.config/matugen/templates/secondary'
output_path = '~/.config/ml4w/colors/secondary'

[templates.on_surface]
input_path = '~/.config/matugen/templates/onsurface'
output_path = '~/.config/ml4w/colors/onsurface'

#[templates.ohmyposh]
#input_path = '~/.config/matugen/templates/ohmyposh-colors.json'
#output_path = '~/.config/ohmyposh/colors.json'
#post_hook = "jq --slurpfile palette ~/.config/ohmyposh/colors.json '. + $palette[0]' ~/.config/ohmyposh/EDM115-newline.omp.json > /tmp/new_theme.json && mv /tmp/new_theme.json ~/.config/ohmyposh/EDM115-newline.omp.json"

[templates.vscode]
input_path = '~/.config/matugen/templates/vscode.json'
output_path = '~/.config/Code - OSS/User/settings.json'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/alacritty-colors.toml'
