[General]
closeToTray=false
daemonAddress=localhost
daemonPort=11987
daemonSSLEnabled=false
networkCookies="@ByteArray(cc=TUE51tNM1o2mJHWuLVa6Kg5c4foykPUrHP7Uqajnrky3HVawHL7a/fU+hPYdZt1AV5M=; HttpOnly; expires=Sat, 11-Apr-2026 23:23:44 GMT; domain=localhost; path=/\n)"
startInTray=false
startupDelay=0
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xee\0\0\x2\xa5\0\0\0\0\0\0\0\0\0\0\x4\xee\0\0\x2\xa5\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xee\0\0\x2\xa5)
zoomFactor=1
