[General]
closeToTray=false
daemonAddress=localhost
daemonPort=11987
daemonSSLEnabled=false
networkCookies="@ByteArray(cc=0hQyGVqt6uUefYyz+V+stdkN2+SoCXC3cKuk4JBk6HjhRaPoMCeN8IJ7UecOiI+N8fk=; HttpOnly; expires=Wed, 13-May-2026 22:55:06 GMT; domain=localhost; path=/\n)"
startInTray=false
startupDelay=0
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xee\0\0\x2\xa5\0\0\0\0\0\0\0\0\0\0\x4\xee\0\0\x5W\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xee\0\0\x2\xa5)
zoomFactor=1
